[package]
name = "chatgpt-at-home"
version = "0.1.0"
license = "MIT"
authors = ["Patryk Wychowaniec <pwychowaniec@pm.me>"]
edition = "2021"

[dependencies]
rand = "0.8.5"
rustyline = "11.0.0"

[dev-dependencies]
test-case = "3.0.0"
